version: "3.9"
services:
  nginx:
    restart: unless-stopped
    build: ./requirements/nginx/
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wp-site:/www/wordpress
    networks:
      - backend
    depends_on:
      - wordpress

  mariadb:
    restart: unless-stopped
    build: ./requirements/mariadb/
    image: mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
    env_file:
      - .env

  wordpress:
    restart: unless-stopped
    build: requirements/wordpress/
    image: wordpress
    volumes:
      - wp-site:/www/wordpress
    networks:
      - backend
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env

  adminer:
    restart: unless-stopped
    build: requirements/bonus/adminer/
    image: adminer
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - mariadb

  redis:
    restart: unless-stopped
    build: requirements/bonus/redis/
    image: redis
    networks:
      - backend

  ftp:
    restart: unless-stopped
    build: requirements/bonus/ftp/
    image: ftp
    networks:
      - backend
    ports:
      - "21:21"
      - "21000:21000"
    volumes:
      - wp-site:/home/admin/

  site:
    restart: unless-stopped
    build: requirements/bonus/site/
    image: site
    networks:
      - backend
    ports:
      - "9000:9000"

  backup:
    restart: unless-stopped
    build: requirements/bonus/backup/
    image: backup
    networks:
      - backend
    depends_on:
      - mariadb
    volumes:
      - wp-site:/db
      - backup:/backup

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/dolphin/data/db
      o: bind

  wp-site:
    driver: local
    driver_opts:
      type: none
      device: /home/dolphin/data/wp-site
      o: bind

  backup:
    driver: local
    driver_opts:
      type: none
      device: /home/dolphin/data/backup
      o: bind

networks:
  backend:
    driver: bridge
